### ISSUE TITLE
PouchDB: SIGSEGV just by importing the package

### ISSUE THREAD

**Issue by odiferousmint** [go-kivik/kivik#424]
$ cat pouchdb.go

```go
package main

import (
  _ "github.com/go-kivik/kivik"
  _ "github.com/go-kivik/pouchdb"
)

func main() {
}
```

    $ go run pouchdb.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x649d72]

goroutine 1 [running]:
github.com/gopherjs/gopherjs/js.(*Object).Get(0x0, 0x6f3853, 0x4, 0x7522c0)
        /home/odiferousmint/go/src/github.com/gopherjs/gopherjs/js/js.go:32 +0x22
github.com/go-kivik/pouchdb/bindings.init()
        /home/odiferousmint/go/src/github.com/go-kivik/pouchdb/bindings/pouchdb.go:243 +0x89
```

Versions:

```
github.com/gopherjs/gopherjs - ce3c9ade29deed38a85f259f40e823cc17213830
github.com/go-kivik/kivik    - 6c848b606af7c63a9ccdfab076f9f38e6e7bf895
github.com/go-kivik/pouchdb  - d5acb4787b834535395c207e88d73f30f0e94e92

go version go1.13.3 linux/amd64
```

**Comment by flimzy** [comment]
The PouchDB driver requires JavaScript, so must be executed with `gopherjs`, not `go`.

**Comment by odiferousmint** [comment]
Oh, I see. Well, in that case feel free to close the issue.

Though I must ask, what am I supposed to use at the backend if I am using `PouchDB` in my frontend?

**Comment by flimzy** [comment]
I don't understand your question. PouchDB on the frontend usually requires nothing on the backend.
